Metrics
channable/hoff pull request #194
Opened 2023-01-02 13:34 UTC by DiegoDiverio

Fixes part of https://github.com/channable/hoff/issues/99 by showing Prometheus-readable metrics on a configurable port, only showing one metric (number of PRs merged) at the moment. Other metrics would be easier to add now, but they should be described in new issues, in more specific detail, when the need arises.

2023-01-02 16:01 UTC, bertptrs reviewed
I don't read Haskell very well so I can't comment too much, but I have one suggestion

Right now we have a single counter for the number of PRs merged. This is not that helpful if you have many projects in a single instance like we do. Perhaps we could add a `project` label to the counter and track the metric by project?

2023-01-02 16:11 UTC, DiegoDiverio commented
> I don't read Haskell very well so I can't comment too much, but I have one suggestion
> 
> Right now we have a single counter for the number of PRs merged. This is not that helpful if you have many projects in a single instance like we do. Perhaps we could add a `project` label to the counter and track the metric by project?

Sorry for the lack of clarity, that's what it already does!

2023-01-02 16:24 UTC, FPtje requested changes
Thanks for the PR! This is going to give some wonderful insights!

Some comments, and a general note:

Could you test this PR and make sure:

- The counter is indeed increased when a PR is merged
- The /metrics endpoint gives a good output (you could post it in this PR)

2023-01-02 16:24 UTC, FPtje commented on app/Main.hs
> +projectThread :: Configuration
Thanks for splitting up this function from the main function. That makes the code more readable!

2023-01-02 16:24 UTC, FPtje commented on app/Main.hs
> +      -- Implement a newtype for a logging monad that also embodies MonadMonitor
I'm not sure I understand this comment. This code does not implement a newtype. That is done in `Metrics/Metrics.hs`. Two lines below, the `Metrics.runLoggingMonitorT` does force the monad to be a `LoggingMonitorT`

2023-01-03 15:16 UTC, FPtje approved these changes
Awesome, one nit but otherwise LGTM!

2023-01-03 15:16 UTC, FPtje commented on src/Configuration.hs
> +    metricsHost :: String
For consistency this should be a `Text`.

2023-01-03 15:16 UTC, FPtje commented on src/Metrics/Metrics.hs
> +  { projectMetricsMergedPR     :: Vector ProjectLabel Counter
Nit: The indentation of the `::` seems arbitrary here

2023-01-03 15:39 UTC, FPtje approved these changes
Awesome!

2023-01-03 15:41 UTC, DiegoDiverio commented
@OpsBotPrime merge

2023-01-03 15:41 UTC, OpsBotPrime commented
Pull request approved for merge by @DiegoDiverio, rebasing now.

2023-01-03 15:42 UTC, OpsBotPrime commented
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/a16923f0-b2cd-4983-8f0a-143f2e2dbde4?pipeline_id=e8f29855-ef34-4bfa-a484-7a9a4d8ba0b9) started.

2023-01-03 15:47 UTC, merged