Subprojects in deploy command
channable/hoff pull request #232
Opened 2023-08-04 11:25 UTC by alex-mckenna

This PR adds the ability to specify specific subprojects to deploy. This makes it possible to write things like

  - merge and deploy foo
  - merge and deploy foo, bar
  - merge and deploy foo, bar to environment
  - merge and deploy foo, bar on friday

Merge commits will include an additional line `Deploy-Subprojects:` with a value of either `all`, or a comma-separated list of the subprojects to deploy.

2023-08-05 11:10 UTC, robbert-vdh requested changes

2023-08-05 11:10 UTC, robbert-vdh commented on src/Logic.hs
> +    pMergeWindow = (OnFriday <$ P.try (P.hspace *> pString "on friday")) <|> pure NotFriday
It's Saturday and I just happened to see this on my GitHub feed. :see_no_evil: 
But before I look over this when I review the PR next week, these `hspace1` to `hspace` changes are not correct. The comments also explicitly mention these parsers having to consume a space character first. With your parser changes you can now `merge and deployto productionon friday`.

2024-01-02 13:51 UTC, rkrzr commented
Looks like this PR was forgotten. Do we still want this @alex-mckenna ?

2024-01-02 14:19 UTC, Riscky commented
> Do we still want this

This is necessary for one of the (preliminary) devops OKRs for Q1: Deploydocus for Sharkmachine. This because we don't want to deploy _all_ Sharkmachine subprojects for each new version.

2024-02-07 15:48 UTC, alex-mckenna commented
Stale, outdated, will replace with the nicer impl in [this branch](https://github.com/channable/hoff/tree/subprojects-command) when it has some more tests around the main logic

2024-02-07 15:48 UTC, closed without merging