Use reactions for confirmation when appropriate
channable/hoff pull request #272
Opened 2024-09-10 13:40 UTC by isomorpheme

Closes #198.

2024-09-26 11:10 UTC, isomorpheme commented
Example of my local hoff using reactions: https://github.com/isomorpheme/sandbox/pull/2

2024-09-26 12:20 UTC, RileyApeldoorn requested changes
source code itself looks good, but could you add a test case for this (or point me to something that tests this particular feature if i overlooked it)?

2024-09-26 13:21 UTC, isomorpheme commented on src/Types.hs
> +  -- doesn't seem to be a REST endpoint for that, despite it being possible through the UI.
It seems that they do - I used devtools to look at the outgoing requests when adding a reaction, and that doesn't seem to use the REST API.

2024-09-26 13:45 UTC, isomorpheme commented
> could you add a test case for this (or point me to something that tests this particular feature if i overlooked it)?

I already added test cases here: https://github.com/channable/hoff/pull/272/files#diff-5057de5eb61e3ca52c8f206f6964e0486e9257418d5d39ab89f3cfaaf6e97839R913-R992

Very understandable if you missed that though, the diff is unfortunately large & has a lot of repetition.

2024-09-26 13:52 UTC, RileyApeldoorn approved these changes
neat! thank you :3

2024-09-26 13:52 UTC, RileyApeldoorn commented on src/Types.hs
> +  -- doesn't seem to be a REST endpoint for that, despite it being possible through the UI.
very sad... thanks for looking into it ^^

2024-09-26 13:53 UTC, RileyApeldoorn commented on src/Github.hs
> +        <|> pure Nothing)
it is!

2024-10-03 08:50 UTC, OpsBotPrime commented
<!-- Hoff: ignore -->
Pull request approved for merge by @isomorpheme, waiting for rebase behind one pull request.

2024-10-03 08:50 UTC, OpsBotPrime commented
<!-- Hoff: ignore -->
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/cd985cce-be92-40e7-b1dc-5a7507fd084c?pipeline_id=068c40fe-b8ec-4ffd-bfe5-0828bef7d690) started.

2024-10-03 08:58 UTC, merged