Tag when merge and deploy
channable/hoff pull request #94
Opened 2021-12-01 15:08 UTC by ReinierMaas

When calling `merge and deploy` we currently tag the branch from a CI run on the base branch. Instead, we reduce the time it takes from 3 to 2 CI runs by tagging from Hoff. One CI run on the testing branch and one to build the tag.

2021-12-02 09:07 UTC, maartenberg requested changes
As discussed yesterday: our "tag and deploy" machinery ultimately depends on the string "autodeploy" being somewhere in the tag message (automated tags default to "v1234 (autodeploy)").

Could you ensure that tags created for a `merge and deploy` command get "autodeploy" in their message?

2021-12-07 10:46 UTC, maartenberg approved these changes
LGTM, thanks for adding this!

I have one minor suggestion, feel free to merge afterwards:

2021-12-07 10:46 UTC, maartenberg commented on src/Logic.hs
> +              changelog = maybe "no changelog" id mChangelog
Suggestion: AIUI we should only get a `Nothing` here if Hoff fails to get the changelog, not if there is no changelog, in the unlikely case where the previous tag already points to the commit that Hoff tagged I think it should give an empty string as changelog with exit code 0 (see e.g. `git shortlog HEAD..HEAD`).

I suggest making it clearer that something failed:

```suggestion
              changelog = maybe "Failed to get changelog" id mChangelog
```

2021-12-07 11:01 UTC, ReinierMaas commented
@OpsBotPrime merge!

2021-12-07 11:01 UTC, OpsBotPrime commented
Pull request approved for merge by @ReinierMaas, rebasing now.

2021-12-07 11:01 UTC, OpsBotPrime commented
Rebased as 3d25cfd71ea93782e7bae90f7d9be8e6ea2b0278, waiting for CI …

2021-12-07 11:05 UTC, merged